### ISSUE TITLE
I'd like to change how errors are handled

### ISSUE THREAD

**Issue by miracle2k** [graphql-python/graphql-server-core#10]
I strongly dislike the fact that this library seems to catch any and all exceptions, and returns them as an error response.

If I have a bug in my resolver code, this should be a 500 error, be tracked to Sentry, and the error message should not be exposed to the user.

If the user makes a mistake in their query, this should be a 400 error, with a clear message, and should not go to Sentry.

As it stands, this library (and thus all the integrations) do not seem to let me do this. I just get an error response, and I'd have to reverse engineer which class of error it is.

**Comment by miracle2k** [comment]
It seems what is really happening is this:

- graphql-core itself already catches all errors.
- graphql-server-core return the result from graphql-core as-is.
- sanic_graphql then calls again into `graphql-server-core`, namely the `encode_execution_results` helper. This one essentially returns the data for an HTTP response (status code and so on). It passes through a `format_error` callback.

I guess what I want to do is override this `format_error` callback, and raise an exception there.

    class MyGraphQLView(GraphQLView):

        @staticmethod
        def format_error(error):
            # graphene likes to wrap all of the exceptions, unwrap
            if isinstance(error, GraphQLLocatedError):
                error = error.original_error

            # Is this an error we want to pass through?
            if isinstance(error, GraphQLError):
                return graphql.error.format_error(error)
            else:
                # Unknown error, crash
                raise error

**Comment by miracle2k** [comment]
I think this is a bit confusing to achieve what I would perceive to be the "default" approach, but I am not sure if there is something actionable here right now from my point of view.

**Comment by kaos** [comment]
Most Excellent. This ought to be in the docs.

However, that seems to apply to the now legacy version https://github.com/graphql-python/graphql-core-legacy as I don't find the GraphQLLocatedError in the new core, which seems to loose the original exception type, as they only use the `str(e.message)` part of it!?
