### ISSUE TITLE
Correct way to return 401 from middleware

### ISSUE THREAD

**Issue by alexchamberlain** [graphql-python/graphql-server-core#15]
Is it possible to return a 401 error from middleware? I've tried raising an HTTPQueryError, but it's being intercepted and returned as JSON, with 200 status.

**Comment by ProjectCheshire** [comment]
@alexchamberlain Better late than never - I use to return those. 
```python
class GraphExecutionError(GraphQLError):
    def __init__(self, message, code=None, params=None):
        super().__init__(message)
        self.message = str(message)
        self.code = code
        self.params = params
``

**Comment by RyanZotti** [comment]
@ProjectCheshire that didn't change the response code for me. This [comment](https://github.com/graphql-python/graphene/issues/142#issuecomment-221290862) suggests it's not possible to alter the response code. `200` and `500` are your only options.
