### ISSUE TITLE
Asynchronous Support

### ISSUE THREAD

**Issue by mgenti** [graphql-python/graphql-server-core#2]
I was looking through the code in __init__.py to try and adapt the "return_promise" option to work with Tornado's IOLoop. I started with the example in the sanic-graphql repository.

Looking through how the graphql-server package uses the promise library it looks like the query is always executed immediately. I believe this is due to the fact that the executor never yields anything for an event loop to iterate on.

I have not used the promise library before so I might be missing something. Could you help me clarify how to use graphql-server asynchronously?

**Comment by dpnova** [comment]
I've got it working in sanic, which is an async framework, maybe check out the https://github.com/graphql-python/sanic-graphql implementation?
