### ISSUE TITLE
Release new package version

### ISSUE THREAD

**Issue by obi1kenobi** [graphql-python/graphql-server-core#28]
Loving this awesome and extremely useful package, thank you for maintaining it!

I was hoping to use the ability to pass in custom executors introduced in [the following commit](https://github.com/graphql-python/graphql-server-core/commit/786849b2ada27b3e6cccb2164765a157eaf8b983), but it appears that the newest published version (`1.1.1`) was released before that commit was merged.

Would it be possible to release the current `master` branch any time soon? I'm hoping to avoid having to install from a git commit hash :)

Thanks again!

**Comment by Cito** [comment]
I'm trying to get this finally done, and created a 1.1.2 tag waiting to be released. The problem is that currently there is no PyPI deployment password configured - we need one of the PyPI mainteiners @syrusakbary or @mvanlonden to add this.

**Comment by Cito** [comment]
Version 1.1.2 has now been released. Thanks to @mvanlonden for adding the PyPI deployment credentials.
