### ISSUE TITLE
Queries are parsed twice

### ISSUE THREAD

**Issue by jnak** [graphql-python/graphql-server-core#43]
Hi,

Just noticed as I was reading trough the codebase that queries are currently parsed twice. Once in [`get_response`](https://github.com/graphql-python/graphql-server-core/blob/master/graphql_server/__init__.py#L241) and another time by `graphql`. Ideally, both should share the same document backend so we can keep query parsing to a minimum.

I'm not planning to send a PR as I'm not currently a user of this library. Just wanted to report it in case no one knew about it.

Cheers,
J

**Comment by KingDarBoja** [comment]
Hi @jnak 

I am aware of this little duplication but had to left that parsing as the subsequent [code](https://github.com/graphql-python/graphql-server-core/blob/master/graphql_server/__init__.py#L248) makes use of it in order to throw an error about the allowed operation type.

I need to dig a bit more on the graphql-core code to see if I can get rid of it.

Cheers!

**Comment by jnak** [comment]
In GraphQL V2, we can avoid the double parsing by using a [cached backend](https://github.com/graphql-python/graphql-core-legacy/blob/8f7c8f3351dd0a4580b87f293aed7bfcf9126bc4/graphql/backend/cache.py#L42):
```py
def get_response(schema, ..., document=None, **kwarg):
    ...
    try:
        document = backend.document_from_string(schema, params.query)
    except GraphQLError as e:
        return ExecutionResult(data=None, errors=[e])
```
We would not need to change Flask-GraphQL since it already allows user to pass a [backend](https://github.com/graphql-python/flask-graphql/blob/master/flask_graphql/graphqlview.py#L89).

We can't do that in GraphQL V3 since there is no concept of backends, but we might not need to since it will [return parsing errors](https://github.com/graphql-python/graphql-core/blob/6687b168b82e6c1722bb9748430f8785cabe46f5/src/graphql/graphql.py#L174) as an `ExecutionError`. That said, there should really be a way in GraphQL V3 to pass a query document (vs just a string), so callers have a chance to cache the parsing of the string.

**Comment by Cito** [comment]
> there should really be a way in GraphQL V3 to pass a query document (vs just a string), so callers have a chance to cache the parsing of the string

The API to do that in GraphQL-core v3 and GraphQL.js is the  `execute()` function. In fact the `graphql()` and `graph_sync()` functions are only thin wrappers around that function, with additional parsing and validation steps.  If you want to have more control over the parsing and validation, you need to do run these steps manually and then call `execute()`. Just look at the implementation in the `graphql` module to see how you do the parsing and validation (it's very simple, don't worry).

**Comment by jnak** [comment]
Great - makes a lot of sense. Thanks for the clarification @Cito!
