### ISSUE TITLE
Update README Integrations: minimal WSGI Application

### ISSUE THREAD

**Issue by moritzmhmk** [graphql-python/graphql-server-core#9]
Since I did not find a minimal implementation to get graphql running as a WSGI Application (without a framework like django or flask) I created one only depending on ``graphql-server-core``.

For the next developer searching for this it might be useful to add [wsgi-graphql](https://github.com/moritzmhmk/wsgi-graphql) to Integrations in the README.

**Comment by Cito** [comment]
Thank you @moritzmhmk - the README will be updated in #19 now.
